on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller ocpbugpull.py --hidden-import pandas --onefile
    # Optionally verify that it works (provided that it does not need user interaction)
    - run: ./dist/ocpbugpull/ocpbugpull
    - uses: actions/upload-artifact@v2
      with:
        path: dist/*
